### ISSUE TITLE
Affichage des disponibilités d'une salle qui n'existe pas

### ISSUE THREAD

**Issue by floporsch911** [SLATTY54/GL02_Mettez_Nous_A#1]
Lorsque l'on demande une salle qui n'existe pas, le logiciel nous renvoie que la salle est disponible sur tous les créneaux de la journée. Il nous faudrait un retour disant que la salle n'existe pas. 
Exemple : 
Lorsque l'on tape cette commande : node .\CaporalCli.js availableSlots ./data/edt.cru CX30
On ne se trouve pas face à une erreur mais face à tout les créneaux possible d'une journée.

**Comment by SLATTY54** [comment]
Vérification de l'existence de la salle dans l'implementation de la commande *availableSlots* : <br><code>let salleExist = false;
				analyzer.parsedCRU.forEach(cours => {
					if (cours.salle === salleToSearch) {
						salleExist = true;
					}
				});
				if (!salleExist) {
					logger.info('Cette salle n\'existe pas');
					return;
				}</code>
