### ISSUE TITLE
Affichage du jour des disponibilités d'une salle

### ISSUE THREAD

**Issue by floporsch911** [SLATTY54/GL02_Mettez_Nous_A#2]
Lorsque l'on rentre un numéro de salle, Le logiciel nous donne les créneaux auxquels la salle est disponible mais pas le jour de la semaine. Nous ne savons donc pas à quel jour correspondent les horaires affichés.
Exemple : 
Si on rentre : node .\CaporalCli.js availableSlots ./data/edt.cru C103
On nous donne les horaires où son disponible cette salle mais pas le jour.
Il faudrait pouvoir donner le jour en plus des horaires pour que le résultat soit plus pertinent.

**Comment by SLATTY54** [comment]
Ajout d'une liste de jours permettant de les attribuées pour chaque slots libre.
